### ISSUE TITLE
surge配置有两项目rule 失效了 拉取不到了

### ISSUE THREAD

**Issue by Smecta** [zxfccmm4/Surge#3]
![CleanShot 2024-06-04 at 11 24 59@2x](https://github.com/zxfccmm4/Surge/assets/30615458/0cff9bc3-5b18-41a2-a9e1-29f74abbc1be)
![CleanShot 2024-06-04 at 11 25 07@2x](https://github.com/zxfccmm4/Surge/assets/30615458/f6205763-a70c-4ff1-b9d4-28becafa1636)
# > > Unbreak 后续规则修正
RULE-SET,https://gh.surgee.me/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list,DIRECT
# > PayPal
RULE-SET,https://gh.surgee.me/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/PayPal.list,🇺🇸 United States
请修正

**Comment by zxfccmm4** [comment]
已经处理，重新拉取配置即可。

**Comment by Smecta** [comment]
> https://gh.surgee.me/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list,DIRECT

https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Unbreak.list
我看更新了之后 变成这个地址了，但是这个地址已经404了，
